### ISSUE TITLE
Don't think tbb.dll is needed any more

### ISSUE THREAD

**Issue by craftwar** [LoLUpdater/LoLUpdater#1]
Garena lol is tested
I don't see tbb.dll in directory. I use process explorer(from sysinternals) to find out tbb.dll is not listed as loaded dlls.

**Comment by Loggan08** [comment]
What about FPS?

**Comment by craftwar** [comment]
Do you mean nvidia CG? still used.

Same, riot lol is not tested. I think there may be no tbb.dll in a clean install.

I don't know it's listed or not if riot loads tbb.dll from .wad archive.
In this case, we can't modify .wad to use another tbb.dll.

**Comment by Loggan08** [comment]
FPS with/without the modified tbb.dll file.

Can you make a test (Install/Restore) ?

**Comment by craftwar** [comment]
It doesn't load tbb.dll with/without tbb.dll in game exe folder. I think it won't make difference.

May be statical link or they don't use it any more.

**Comment by Loggan08** [comment]
It might be statical link, I will investigate further in a few moments.

**Comment by craftwar** [comment]
Is tbb.dll still in clean riot lol install?

Garena removes it since 7.x version.

**Comment by Loggan08** [comment]
In Riot version / China LOL it's still there.

**Comment by craftwar** [comment]
Change garena region to east Asia (tw, ph , sg...etc) or main regions.

Singapore may be best choice.

**Comment by Loggan08** [comment]
I believe you it's not there, there is not much I can do about this issue though.

**Comment by craftwar** [comment]
I am in Taiwan, just curious why you are updating tbb.dll. That's why I report this to let you know.

I don't expect you can handle this, it's not easy.

**Comment by Loggan08** [comment]
Well since it's gone now in Garena it used to boost FPS (main component)
It's still there in Riot/China so I'll keep it.

**Comment by Loggan08** [comment]
If you want further contact you can reach me on skype: Ikorsu
